**Imports**

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

**Importing our dataset**

In [3]:
credit_risk = pd.read_csv("credit_risk_dataset.csv")
credit_risk.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

**Data Exploration**

In [4]:
credit_risk.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [5]:
credit_risk_copy =  credit_risk.copy()

In [6]:
credit_risk.pivot_table(index='person_age', columns='loan_status', values='person_income', aggfunc='count').reset_index().sort_values(by='person_age', ascending=False)

loan_status  person_age       0      1
57                  144     3.0    NaN
56                  123     2.0    NaN
55                   94     1.0    NaN
54                   84     1.0    NaN
53                   80     1.0    NaN
52                   78     1.0    NaN
51                   76     1.0    NaN
50                   73     3.0    NaN
49                   70     5.0    2.0
48                   69     5.0    NaN
47                   67     1.0    NaN
46                   66     6.0    3.0
45                   65     6.0    3.0
44                   64     6.0    1.0
43                   63     2.0    1.0
42                   62     4.0    3.0
41                   61     5.0    4.0
40                   60     8.0    7.0
39                   59     5.0    NaN
38                   58    16.0    3.0
37                   57    11.0    4.0
36                   56    14.0    1.0
35                   55    13.0    7.0
34                   54    17.0    7.0
33                   53    23.0    7.0
32                   52    24.0   12.0
31                   51    31.0    8.0
30                   50    40.0   12.0
29                   49    37.0   12.0
28                   48    55.0   20.0
27                   47    79.0   15.0
26                   46    82.0   12.0
25                   45    81.0   27.0
24                   44   114.0   27.0
23                   43   135.0   29.0
22                   42   138.0   50.0
21                   41   199.0   42.0
20                   40   214.0   57.0
19                   39   233.0   69.0
18                   38   311.0   62.0
17                   37   381.0   97.0
16                   36   425.0  123.0
15                   35   492.0  128.0
14                   34   570.0  139.0
13                   33   683.0  173.0
12                   32   771.0  193.0
11                   31   907.0  235.0
10                   30  1056.0  260.0
9                    29  1344.0  343.0
8                    28  1440.0  414.0
7                    27  1694.0  444.0
6                    26  1960.0  517.0
5                    25  2362.0  675.0
4                    24  2780.0  769.0
3                    23  3056.0  833.0
2                    22  2749.0  884.0
1                    21   857.0  372.0
0                    20    13.0    2.0

In [7]:
# removing people with more than 70 years old
cr_age_removed = credit_risk[credit_risk['person_age']<=70]

In [8]:
# removing people with more than 70 years old
cr_age_removed = credit_risk[credit_risk['person_age']<=70]
cr_age_removed.reset_index(drop=True, inplace=True)
cr_age_removed.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [9]:
credit_risk.shape

(32581, 12)

In [10]:
cr_age_removed.shape

(32568, 12)

In [11]:
# lets deal with length of employment
cr_age_removed.pivot_table(index='person_emp_length', columns='loan_status', values='person_income', aggfunc='count').reset_index().sort_values(by='person_emp_length', ascending=False)

loan_status  person_emp_length       0       1
34                       123.0     1.0     1.0
33                        38.0     1.0     NaN
32                        34.0     NaN     1.0
31                        31.0     4.0     NaN
30                        30.0     1.0     1.0
29                        29.0     NaN     1.0
28                        28.0     3.0     NaN
27                        27.0     4.0     1.0
26                        26.0     5.0     1.0
25                        25.0     8.0     NaN
24                        24.0     7.0     3.0
23                        23.0     6.0     3.0
22                        22.0    16.0     3.0
21                        21.0    28.0    10.0
20                        20.0    29.0    13.0
19                        19.0    55.0     9.0
18                        18.0    93.0    11.0
17                        17.0   107.0    22.0
16                        16.0   145.0    20.0
15                        15.0   195.0    43.0
14                        14.0   279.0    56.0
13                        13.0   375.0    51.0
12                        12.0   484.0    90.0
11                        11.0   604.0   136.0
10                        10.0   577.0   119.0
9                          9.0  1123.0   244.0
8                          8.0  1406.0   281.0
7                          7.0  1781.0   412.0
6                          6.0  2166.0   500.0
5                          5.0  2398.0   548.0
4                          4.0  2262.0   610.0
3                          3.0  2760.0   696.0
2                          2.0  2860.0   987.0
1                          1.0  2108.0   806.0
0                          0.0  2956.0  1147.0

In [12]:
# Removing any person employed over 47 years i.e from 18-65 yrs
person_emp_removed = cr_age_removed[cr_age_removed['person_emp_length']<=47]
person_emp_removed.reset_index(drop=True, inplace=True)
person_emp_removed.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2

In [13]:
person_emp_removed.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,31671.000000,3.167100e+04,31671.000000,31671.000000,28626.000000,31671.000000,31671.000000,31671.000000
mean,27.717754,6.649231e+04,4.780714,9660.637492,11.040070,0.215497,0.169621,5.804395
std,6.159859,5.277413e+04,4.028718,6334.716643,3.229507,0.411173,0.106275,4.048776
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.936600e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.600000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,8.000000e+04,7.000000,12500.000000,13.480000,0.000000,0.230000,8.000000
max,70.000000,2.039784e+06,38.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [14]:
# Dealing with null values
person_emp_removed.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length                0
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3045
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [15]:
cr_data = person_emp_removed.copy()
cr_data.shape

(31671, 12)

In [16]:
cr_data.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2

In [17]:
cr_data.fillna({'loan_int_rate':cr_data['loan_int_rate'].median()}, inplace=True)

In [18]:
cr_data.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [19]:
cr_data.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,31671.000000,3.167100e+04,31671.000000,31671.000000,31671.000000,31671.000000,31671.000000,31671.000000
mean,27.717754,6.649231e+04,4.780714,9660.637492,11.035256,0.215497,0.169621,5.804395
std,6.159859,5.277413e+04,4.028718,6334.716643,3.070364,0.411173,0.106275,4.048776
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.936600e+04,2.000000,5000.000000,8.490000,0.000000,0.090000,3.000000
50%,26.000000,5.600000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,8.000000e+04,7.000000,12500.000000,13.160000,0.000000,0.230000,8.000000
max,70.000000,2.039784e+06,38.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [20]:
# Number of records
cr_data.groupby('loan_status').count()['person_age']

loan_status
0    24846
1     6825
Name: person_age, dtype: int64

In [21]:
6825/(6825+24846)

0.21549682675002368

In [22]:
cr_data.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2

In [23]:
cr_data.groupby('person_home_ownership').count()['loan_intent']

person_home_ownership
MORTGAGE    13088
OTHER         107
OWN          2410
RENT        16066
Name: loan_intent, dtype: int64

In [24]:
cr_data.groupby('loan_intent').count()['person_home_ownership']

loan_intent
DEBTCONSOLIDATION    5064
EDUCATION            6288
HOMEIMPROVEMENT      3510
MEDICAL              5891
PERSONAL             5365
VENTURE              5553
Name: person_home_ownership, dtype: int64

In [25]:
cr_data_copy = cr_data.drop('loan_grade',axis=1)

In [26]:
cr_data_copy.shape

(31671, 11)

**Categorical Features Treatment**

In [27]:
cr_data_categorical_treated = cr_data_copy.copy()

In [28]:
# check categories in this data
cr_data_categorical_treated.groupby('person_home_ownership').count()['person_age']

person_home_ownership
MORTGAGE    13088
OTHER         107
OWN          2410
RENT        16066
Name: person_age, dtype: int64

In [29]:
person_home_ownership = pd.get_dummies(cr_data_categorical_treated['person_home_ownership'], drop_first=True).astype(int)
person_home_ownership.head()

   OTHER  OWN  RENT
0      0    1     0
1      0    0     0
2      0    0     1
3      0    0     1
4      0    1     0

In [30]:
loan_intent = pd.get_dummies(cr_data_categorical_treated['loan_intent'], drop_first=True).astype(int)
loan_intent.head()

   EDUCATION  HOMEIMPROVEMENT  MEDICAL  PERSONAL  VENTURE
0          1                0        0         0        0
1          0                0        1         0        0
2          0                0        1         0        0
3          0                0        1         0        0
4          0                0        0         0        1

In [31]:
cr_data_categorical_treated['cb_person_default_on_file_binary'] = np.where(cr_data_categorical_treated['cb_person_default_on_file']=='Y',1,0)
cr_data_categorical_treated.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,cb_person_default_on_file_binary
0,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2,0
1,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3,0
2,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2,0
3,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4,1
4,21,9900,OWN,2.0,VENTURE,2500,7.14,1,0.25,N,2,0

In [32]:
# Remove columns which are not required
data_to_scale = cr_data_categorical_treated.drop(['person_home_ownership', 'loan_intent', 'loan_status', 'cb_person_default_on_file_binary', 'cb_person_default_on_file'], axis=1)

In [33]:
data_to_scale.head()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length
0,21,9600,5.0,1000,11.14,0.10,2
1,25,9600,1.0,5500,12.87,0.57,3
2,23,65500,4.0,35000,15.23,0.53,2
3,24,54400,8.0,35000,14.27,0.55,4
4,21,9900,2.0,2500,7.14,0.25,2

**Scaling our Data**

In [34]:
scaler = StandardScaler()

In [35]:
data_to_scale.columns

Index(['person_age', 'person_income', 'person_emp_length', 'loan_amnt',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length'],
      dtype='object')

In [36]:
scaled_data = scaler.fit_transform(data_to_scale)
scaled_df = pd.DataFrame(scaled_data, columns=['person_age', 'person_income', 'person_emp_length', 'loan_amnt',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length'])
scaled_df.head()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656

In [37]:
scaled_df.shape

(31671, 7)

In [38]:
cr_data_categorical_treated.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,cb_person_default_on_file_binary
0,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2,0
1,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3,0
2,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2,0
3,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4,1
4,21,9900,OWN,2.0,VENTURE,2500,7.14,1,0.25,N,2,0

In [39]:
scaled_data_combined = pd.concat([scaled_df,person_home_ownership,loan_intent],axis=1)
scaled_data_combined['cb_person_default_on_file'] = cr_data_categorical_treated['cb_person_default_on_file_binary']
scaled_data_combined['loan_status'] = cr_data_categorical_treated['loan_status']
scaled_data_combined.head()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,OTHER,OWN,RENT,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,VENTURE,cb_person_default_on_file,loan_status
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656,0,1,0,1,0,0,0,0,0,0
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664,0,0,0,0,0,1,0,0,0,1
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656,0,0,1,0,0,1,0,0,0,1
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671,0,0,1,0,0,1,0,0,1,1
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656,0,1,0,0,0,0,0,1,0,1

In [40]:
scaled_data_combined.groupby('loan_status').count()['EDUCATION']

loan_status
0    24846
1     6825
Name: EDUCATION, dtype: int64

**SMOTE - Sythetic Minority Over-Sampling Technique** 

**Data Balancing**

In [41]:
target = scaled_data_combined['loan_status']
features = scaled_data_combined.drop('loan_status', axis=1)
features.head()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,OTHER,OWN,RENT,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,VENTURE,cb_person_default_on_file
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656,0,1,0,1,0,0,0,0,0
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664,0,0,0,0,0,1,0,0,0
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656,0,0,1,0,0,1,0,0,0
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671,0,0,1,0,0,1,0,0,1
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656,0,1,0,0,0,0,0,1,0

In [42]:
pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in c:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn) (2.2.4)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn) (1.17.0)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn) (1.8.0)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in c:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [43]:
from  imblearn.over_sampling import SMOTE

In [44]:
smote = SMOTE()

In [45]:
balanced_features, balanced_target = smote.fit_resample(features,target)

In [46]:
balanced_features.shape

(49692, 16)

In [47]:
31671

31671

In [48]:
scaled_data_combined.groupby('loan_status').size()

loan_status
0    24846
1     6825
dtype: int64

In [49]:
balanced_target_df = pd.DataFrame({'target':balanced_target})
balanced_target_df.groupby('target').size()

target
0    24846
1    24846
dtype: int64

**Model Training**

In [84]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [51]:
x_train, x_test, y_train, y_test = train_test_split(balanced_features, balanced_target, test_size=0.20,random_state=42)

**Building the models**

1. **Logistic regresion**

In [52]:
logit = LogisticRegression()

In [61]:
logit.fit(x_train,y_train)

LogisticRegression()

In [62]:
logit.score(x_train,y_train)

0.7813749905667496

In [67]:
logit_prediction = logit.predict(x_test)

In [68]:
print(classification_report(y_test, logit_prediction))

              precision    recall  f1-score   support

           0       0.79      0.78      0.78      4995
           1       0.78      0.78      0.78      4944

    accuracy                           0.78      9939
   macro avg       0.78      0.78      0.78      9939
weighted avg       0.78      0.78      0.78      9939

In [70]:
print(logit.coef_[0])

[-0.08625368  0.06655963 -0.03652685 -0.69589473  0.99123578  1.41759154
  0.02619088 -0.77302138 -2.07222717  0.4550547  -1.20917597 -0.36979986
 -0.51343924 -0.98184517 -1.54494067  0.09042733]

In [72]:
# Lets create another Dataframe
features_imp_logit = pd.DataFrame({'features': balanced_features.columns, 'logit_imp':logit.coef_[0]})
features_imp_logit.sort_values(by='logit_imp', ascending=False)

                      features  logit_imp
5          loan_percent_income   1.417592
4                loan_int_rate   0.991236
9                         RENT   0.455055
15   cb_person_default_on_file   0.090427
1                person_income   0.066560
6   cb_person_cred_hist_length   0.026191
2            person_emp_length  -0.036527
0                   person_age  -0.086254
11             HOMEIMPROVEMENT  -0.369800
12                     MEDICAL  -0.513439
3                    loan_amnt  -0.695895
7                        OTHER  -0.773021
13                    PERSONAL  -0.981845
10                   EDUCATION  -1.209176
14                     VENTURE  -1.544941
8                          OWN  -2.072227

2. **Random Forest**

In [74]:
rf = RandomForestClassifier()

In [75]:
rf.fit(x_train, y_train)

RandomForestClassifier()

In [76]:
rf.score(x_train, y_train)

1.0

In [77]:
rf_prediction = (rf.predict(x_test))
rf_prediction

array([0, 0, 0, ..., 0, 0, 1], shape=(9939,))

In [78]:
print(classification_report(y_test, rf_prediction))

              precision    recall  f1-score   support

           0       0.91      0.97      0.94      4995
           1       0.97      0.91      0.94      4944

    accuracy                           0.94      9939
   macro avg       0.94      0.94      0.94      9939
weighted avg       0.94      0.94      0.94      9939

In [80]:
rf.feature_importances_

array([0.06115621, 0.1552806 , 0.07455206, 0.08277663, 0.20747322,
       0.20145878, 0.05827252, 0.00040776, 0.02036213, 0.04820118,
       0.01553935, 0.01699149, 0.00857146, 0.01242797, 0.01795763,
       0.01857101])

In [83]:
# Df for RF
features_imp_rf = pd.DataFrame({'features':balanced_features.columns, 'rf_imp':rf.feature_importances_})
features_imp_rf.sort_values(by='rf_imp', ascending=False)

                      features    rf_imp
4                loan_int_rate  0.207473
5          loan_percent_income  0.201459
1                person_income  0.155281
3                    loan_amnt  0.082777
2            person_emp_length  0.074552
0                   person_age  0.061156
6   cb_person_cred_hist_length  0.058273
9                         RENT  0.048201
8                          OWN  0.020362
15   cb_person_default_on_file  0.018571
14                     VENTURE  0.017958
11             HOMEIMPROVEMENT  0.016991
10                   EDUCATION  0.015539
13                    PERSONAL  0.012428
12                     MEDICAL  0.008571
7                        OTHER  0.000408

**XGBoost Model**

In [85]:
xgb_model = XGBClassifier(tree_method = 'exact')

In [86]:
# Train the model
# model.fit(x_train.values.ravel())
xgb_model.fit(x_train,y_train.values.ravel())

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [87]:
xgb_model.score(x_train,y_train.values.ravel())

0.965335949488089

In [88]:
# Making the predictions
xgb_prediction = xgb_model.predict(x_test)
xgb_prediction

array([0, 0, 0, ..., 0, 0, 1], shape=(9939,))

In [89]:
print(classification_report(y_test,xgb_prediction))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95      4995
           1       0.98      0.91      0.94      4944

    accuracy                           0.95      9939
   macro avg       0.95      0.95      0.95      9939
weighted avg       0.95      0.95      0.95      9939

In [94]:
features_imp_rf = pd.DataFrame({'features':balanced_features.columns, 'rf_imp':rf.feature_importances_})
features_imp_xgb = pd.DataFrame({'features':balanced_features.columns, 'xgb_imp':xgb_model.feature_importances_})
features_imp_xgb.sort_values(by='xgb_imp',ascending=False)

                      features   xgb_imp
8                          OWN  0.171439
5          loan_percent_income  0.130206
9                         RENT  0.119329
14                     VENTURE  0.086408
6   cb_person_cred_hist_length  0.077250
4                loan_int_rate  0.072914
2            person_emp_length  0.057888
11             HOMEIMPROVEMENT  0.057824
10                   EDUCATION  0.057266
1                person_income  0.042720
13                    PERSONAL  0.040339
0                   person_age  0.033056
15   cb_person_default_on_file  0.020411
12                     MEDICAL  0.012099
7                        OTHER  0.011992
3                    loan_amnt  0.008859

In [97]:
features_imp = pd.concat([features_imp_logit,features_imp_rf,features_imp_xgb], axis=1)
features_imp

,features,logit_imp,features,rf_imp,features,xgb_imp
0,person_age,-0.086254,person_age,0.061156,person_age,0.033056
1,person_income,0.066560,person_income,0.155281,person_income,0.042720
2,person_emp_length,-0.036527,person_emp_length,0.074552,person_emp_length,0.057888
3,loan_amnt,-0.695895,loan_amnt,0.082777,loan_amnt,0.008859
4,loan_int_rate,0.991236,loan_int_rate,0.207473,loan_int_rate,0.072914
5,loan_percent_income,1.417592,loan_percent_income,0.201459,loan_percent_income,0.130206
6,cb_person_cred_hist_length,0.026191,cb_person_cred_hist_length,0.058273,cb_person_cred_hist_length,0.077250
7,OTHER,-0.773021,OTHER,0.000408,OTHER,0.011992
8,OWN,-2.072227,OWN,0.020362,OWN,0.171439
9,RENT,0.455055,RENT,0.048201,RENT,0.119329
10,EDUCATION,-1.209176,EDUCATION,0.015539,EDUCATION,0.057266
11,HOMEIMPROVEMENT,-0.369800,HOMEIMPROVEMENT,0.016991,HOMEIMPROVEMENT,0.057824
12,MEDICAL,-0.513439,MEDICAL,0.008571,MEDICAL,0.012099
13,PERSONAL,-0.981845,PERSONAL,0.012428,PERSONAL,0.040339
14,VENTURE,-1.544941,VENTURE,0.017958,VENTURE,0.086408
15,cb_person_default_on_file,0.090427,cb_person_default_on_file,0.018571,cb_person_default_on_file,0.020411

**Further Exploration**

In [108]:
xgb_prediction_df = pd.DataFrame({'test_indices_xgb':x_test.index,'xgb_pred':xgb_prediction})
rf_prediction_df = pd.DataFrame({'test_indices_rf':x_test.index,'rf_pred':rf_prediction})
logit_prediction_df = pd.DataFrame({'test_indices_logit':x_test.index,'logit_pred':logit_prediction})

In [109]:
logit_prediction_df.head()

   test_indices_logit  logit_pred
0               24808           0
1                9935           0
2               14054           0
3                 147           0
4                4070           0

In [110]:
merged_with_orig = cr_data_copy.merge(xgb_prediction_df,left_index=True,right_on='test_indices_xgb',how='left')
merged_with_orig.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,test_indices_xgb,xgb_pred
NaN,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2,0,NaN
9831.0,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3,1,1.0
NaN,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2,2,NaN
NaN,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4,3,NaN
442.0,21,9900,OWN,2.0,VENTURE,2500,7.14,1,0.25,N,2,4,1.0

In [111]:
merged_with_rf = merged_with_orig.merge(rf_prediction_df,left_index=True,right_on='test_indices_rf',how='left')
merged_with_rf.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,test_indices_xgb,xgb_pred,test_indices_rf,rf_pred
NaN,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2,0,NaN,NaN,NaN
NaN,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3,1,1.0,9831.0,NaN
NaN,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2,2,NaN,NaN,NaN
NaN,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4,3,NaN,NaN,NaN
NaN,21,9900,OWN,2.0,VENTURE,2500,7.14,1,0.25,N,2,4,1.0,442.0,NaN

In [112]:
merged_with_final = merged_with_rf.merge(logit_prediction_df,left_index=True,right_on='test_indices_logit',how='left')
merged_with_final.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,test_indices_xgb,xgb_pred,test_indices_rf,rf_pred,test_indices_logit,logit_pred
NaN,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2,0,NaN,NaN,NaN,NaN,NaN
NaN,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3,1,1.0,9831.0,NaN,NaN,NaN
NaN,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2,2,NaN,NaN,NaN,NaN,NaN
NaN,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4,3,NaN,NaN,NaN,NaN,NaN
NaN,21,9900,OWN,2.0,VENTURE,2500,7.14,1,0.25,N,2,4,1.0,442.0,NaN,NaN,NaN

In [116]:
merged_with_final.dropna(inplace=True)

In [118]:
final_data_with_pred = merged_with_final.drop(['test_indices_xgb', 'test_indices_rf','test_indices_logit'],axis=1)
final_data_with_pred.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,xgb_pred,rf_pred,logit_pred
7782.0,24,78956,RENT,5.0,MEDICAL,35000,11.11,1,0.44,N,4,1.0,0.0,1.0
7968.0,25,12600,OWN,3.0,PERSONAL,1750,13.61,0,0.14,N,3,0.0,1.0,0.0
9251.0,22,153000,MORTGAGE,5.0,DEBTCONSOLIDATION,24000,15.62,1,0.16,Y,2,1.0,1.0,0.0
5662.0,22,16094,MORTGAGE,2.0,VENTURE,5500,7.14,1,0.34,N,3,1.0,0.0,1.0
143.0,21,18000,OWN,1.0,PERSONAL,2500,11.36,0,0.14,N,3,0.0,1.0,0.0

In [119]:
#export to excel
final_data_with_pred.to_excel("D:\credit risk modelling\pd_prediction.xlsx",index=False)

<>:2: SyntaxWarning: invalid escape sequence '\c'
<>:2: SyntaxWarning: invalid escape sequence '\c'
C:\Users\user\AppData\Local\Temp\ipykernel_7604\502059592.py:2: SyntaxWarning: invalid escape sequence '\c'
  final_data_with_pred.to_excel("D:\credit risk modelling\pd_prediction.xlsx",index=False)